<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>OctoMap</PackageId>
    <Description>OctoMap is a lightweight .NET object mapping library powered by DynaBee-generated runtime mappers.</Description>
    <PackageTags>mapping mapper object-mapping code-generator dynabee octomap elysium</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynaBee" Version="1.2.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="MinVer" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>
</Project>
